language: php

php:
  - 7.2

before_install:
 - curl -s https://getcomposer.org/installer | php
 - php composer.phar install --prefer-source --dev
 - cp config/laminasuserldap.global.php.dist tests/config/autoload/laminasuserldap.global.php
 - mkdir data
 - mkdir data/logs

script:
 - phpunit --configuration ./tests/phpunit.xml --coverage-clover ./build/logs/clover.xml
 - php ./vendor/bin/phpcs --standard=PSR2 ./src/ ./tests/

after_script:
  - php ./vendor/bin/coveralls -v

