<?php
// Generated by Laminas's ./bin/classmap_generator.php
return array(
  'LaminasUserLdap\Module'                                        => __DIR__ . '/Module.php',
  'LaminasUserLdap\Adapter\Ldap'                                  => __DIR__ . '/src/LaminasUserLdap/Adapter/Ldap.php',
  'LaminasUserLdap\Authentication\Adapter\LdapAuth'               => __DIR__ . '/src/LaminasUserLdap/Authentication/Adapter/LdapAuth.php',
  'LaminasUserLdap\Entity\User'                                   => __DIR__ . '/src/LaminasUserLdap/Entity/User.php',
  'LaminasUserLdap\Mapper\User'                                   => __DIR__ . '/src/LaminasUserLdap/Mapper/User.php',
  'LaminasUserLdap\Mapper\UserHydrator'                           => __DIR__ . '/src/LaminasUserLdap/Mapper/UserHydrator.php',
  'LaminasUserLdap\Provider\Identity\LdapIdentityProvider'        => __DIR__ . '/src/LaminasUserLdap/Provider/Identity/LdapIdentityProvider.php',
  'LaminasUserLdap\Provider\Identity\ZfcRbacIdentityProvider'     => __DIR__ . '/src/LaminasUserLdap/Provider/Identity/ZfcRbacIdentityProvider.php',
  'LaminasUserLdap\ServiceFactory\LdapAdapterFactory'             => __DIR__ . '/src/LaminasUserLdap/ServiceFactory/LdapAdapterFactory.php',
  'LaminasUserLdap\ServiceFactory\LdapConfigFactory'              => __DIR__ . '/src/LaminasUserLdap/ServiceFactory/LdapConfigFactory.php',
  'LaminasUserLdap\Service\LdapIdentityProviderFactory'           => __DIR__ . '/src/LaminasUserLdap/ServiceFactory/LdapIdentityProviderFactory.php',
  'LaminasUserLdap\ServiceFactory\LoggerAdapterFactory'           => __DIR__ . '/src/LaminasUserLdap/ServiceFactory/LoggerAdapterFactory.php',
  'LaminasUserLdap\ServiceFactory\UserMapperFactory'              => __DIR__ . '/src/LaminasUserLdap/ServiceFactory/UserMapperFactory.php',
  'LaminasUserLdap\ServiceFactory\ZfcRbacIdentityProviderFactory' => __DIR__ . '/src/LaminasUserLdap/ServiceFactory/ZfcRbacIdentityProviderFactory.php',
  'LaminasUserLdap\ServiceFactory\LaminasUserLdapConfigFactory'       => __DIR__ . '/src/LaminasUserLdap/ServiceFactory/LaminasUserLdapConfigFactory.php',
  'LaminasUserLdapTest\ServiceFactory\LdapAdapterFactoryTest'     => __DIR__ . '/tests/LaminasUserLdapTest/src/ServiceFactory/LdapAdapterFactoryTest.php',
);
